# Generated by Django 3.1.6 on 2026-07-28 16:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoarseBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Coarse Branches',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='website_data/default_profile_pic/default.png', upload_to=users.models.profile_pic_dir_path)),
                ('roll', models.CharField(max_length=30, null=True, unique=True)),
                ('verified_roll', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('year', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(2021), django.core.validators.MaxValueValidator(2026)])),
                ('hometown', models.CharField(blank=True, max_length=100, null=True)),
                ('interests', models.CharField(blank=True, max_length=300, null=True)),
                ('birthday', models.DateField(null=True)),
                ('otp', models.IntegerField(blank=True, max_length=5, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('buddies', models.ManyToManyField(blank=True, related_name='buddies', to=settings.AUTH_USER_MODEL)),
                ('coarse_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.coarsebranch')),
                ('liked_posts', models.ManyToManyField(blank=True, related_name='liked_posts', to='posts.Post')),
                ('requested', models.ManyToManyField(blank=True, related_name='requested', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuddyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_request_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Buddy Requests',
            },
        ),
    ]
